version: '3'
services:
  screen-recorder:
    container_name: screen-recorder
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./blackbox:/opt/blackbox
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ${HOME}/.Xauthority:${HOME}/.Xauthority
    command: python run.py
    environment:
      FPS: "10"
      DISPLAY: unix${DISPLAY}
    privileged: true
    network_mode: host
    restart: always

# http://bahndal.egloos.com/534415