version: '3'
services:
  screen-recorder:
    container_name: screen-recorder
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./blackbox:/opt/blackbox
      - /tmp/.X11-unix/X99:/tmp/.X11-unix/X99
    command: python run.py
    environment:
      FPS: "10"
      DISPLAY: ":0.0"
    privileged: true
    restart: always
