version: '3'
services:
  screen-recorder:
    container_name: screen-recorder
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:.
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /root/.Xauthority:/root/.Xauthority
    command: python run.py
    environment:
      DISPLAY: unix${DISPLAY}
    privileged: true
#    network_mode: host
    restart: always
