version: '3'
services:
  screen-recorder:
    container_name: screen-recorder
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./blackbox:/opt/blackbox
      - /tmp/.X11-unix:/tmp/.X11-unix
    command: python run.py
    environment:
      FPS: "10"
      DISPLAY: "unix${DISPLAY}"
    privileged: true
    network_mode: host
    restart: always
