version: '3'
services:
  screen-recorder:
    container_name: screen-recorder
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./blackbox:/opt/blackbox
    command: python run.py
    environment:
      FPS: 10
    privileged: true
    restart: always
