version: '3'
services:
  screen-recorder:
    container_name: screen-recorder
    build:
      context: .
      dockerfile: Dockerfile
    user: "0:0"
    volumes:
      - ./media:/opt/screen-recorder/media
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /root/.Xauthority:/root/.Xauthority
#    command: python run.py
    command: ./run.sh
    environment:
      FPS: 30
      DISPLAY: unix${DISPLAY}
      MEDIA_DURATION: 7
    restart: always
