version: '3'
services:
  screen-recorder:
    container_name: screen-recorder
    build:
      context: .
      dockerfile: Dockerfile
    user: "1000"
    volumes:
      - ./blackbox:/opt/screen-recorder/blackbox
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /root/.Xauthority:/root/.Xauthority
    command: python run.py
    environment:
      FPS: 30
      DISPLAY: unix${DISPLAY}
    privileged: true
#    network_mode: host
    restart: always
